version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mega
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
